################################################################################
# Copyright (C) 2017 by Ben Heberlein
#
# Redistribution, modification or use of this software in source or binary
# forms is permitted as long as the files maintain this copyright. This file
# was created for the University of Colorado Boulder course Advanced Practical
# Embedded Software Development. Ben Heberlein and the University of Colorado 
# are not liable for any misuse of this material.
#
###############################################################################
##
## @file Makefile
## @brief Builds the object file for memsort system call
## 
## This file is used by the Linux kernel to build the memsort system call.
##
## @author Ben Heberlein
## @date September 16 2017
## @version 1.0
##
###############################################################################

obj-y += memsort.o

